# \u7AEF\u53E3\u914D\u7F6E
server:
  port: 8080

spring:
  application:
    name: mybatis-plus-spring
  # jdbc config
  datasource:
    url: jdbc:mysql://192.168.1.29:3306/mybatis-plus-spring?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

